# Generated by Django 5.2 on 2025-05-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_foodcategory_restaurant_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.foodcategory'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.URLField(default='https://example.com/dish-default.jpg'),
        ),
    ]
