# Generated by Django 5.2 on 2025-05-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dish_category_dish_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='dishes/default.jpg', upload_to='dishes/'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurants/default.jpg', upload_to='restaurants/'),
        ),
    ]
