# Generated by Django 5.2 on 2025-05-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_restaurant_category_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
