# Generated by Django 5.2 on 2025-05-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_restaurant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
    ]
