# Generated by Django 5.2 on 2025-05-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_restaurant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=150, unique=True)),
                ('restaurant_password', models.CharField(max_length=128)),
            ],
        ),
    ]
