# Generated by Django 5.2 on 2025-05-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_placedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='placed_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.placedorder'),
        ),
    ]
