# Generated by Django 5.2 on 2025-05-13 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_placedorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='placed_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 13, 8, 44, 23, 817995, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
