# Generated by Django 5.2 on 2025-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_placedorder_placed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of dishes available or per order.'),
        ),
    ]
